[2024-03-04T21:46:35.981+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrape_to_csv.save_to_csv scheduled__2023-12-03T00:00:00+00:00 [queued]>
[2024-03-04T21:46:36.011+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrape_to_csv.save_to_csv scheduled__2023-12-03T00:00:00+00:00 [queued]>
[2024-03-04T21:46:36.020+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2024-03-04T21:46:36.087+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): save_to_csv> on 2023-12-03 00:00:00+00:00
[2024-03-04T21:46:36.105+0000] {standard_task_runner.py:60} INFO - Started process 1586 to run task
[2024-03-04T21:46:36.130+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'scrape_to_csv', 'save_to_csv', 'scheduled__2023-12-03T00:00:00+00:00', '--job-id', '97', '--raw', '--subdir', 'DAGS_FOLDER/mydag.py', '--cfg-path', '/tmp/tmpc_r3v2qr']
[2024-03-04T21:46:36.149+0000] {standard_task_runner.py:88} INFO - Job 97: Subtask save_to_csv
[2024-03-04T21:46:36.322+0000] {task_command.py:423} INFO - Running <TaskInstance: scrape_to_csv.save_to_csv scheduled__2023-12-03T00:00:00+00:00 [running]> on host 03972fe0138c
[2024-03-04T21:46:36.536+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='nduti' AIRFLOW_CTX_DAG_ID='scrape_to_csv' AIRFLOW_CTX_TASK_ID='save_to_csv' AIRFLOW_CTX_EXECUTION_DATE='2023-12-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-03T00:00:00+00:00'
[2024-03-04T21:46:36.542+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: save_to_csv() missing 1 required positional argument: 'quotes'
[2024-03-04T21:46:36.561+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=scrape_to_csv, task_id=save_to_csv, execution_date=20231203T000000, start_date=20240304T214635, end_date=20240304T214636
[2024-03-04T21:46:36.591+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 97 for task save_to_csv (save_to_csv() missing 1 required positional argument: 'quotes'; 1586)
[2024-03-04T21:46:36.626+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-04T21:46:36.669+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
