[2024-03-04T21:47:58.124+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrape_to_csv.save_to_csv scheduled__2023-12-18T00:00:00+00:00 [queued]>
[2024-03-04T21:47:58.145+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrape_to_csv.save_to_csv scheduled__2023-12-18T00:00:00+00:00 [queued]>
[2024-03-04T21:47:58.146+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2024-03-04T21:47:58.175+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): save_to_csv> on 2023-12-18 00:00:00+00:00
[2024-03-04T21:47:58.188+0000] {standard_task_runner.py:60} INFO - Started process 1735 to run task
[2024-03-04T21:47:58.196+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'scrape_to_csv', 'save_to_csv', 'scheduled__2023-12-18T00:00:00+00:00', '--job-id', '145', '--raw', '--subdir', 'DAGS_FOLDER/mydag.py', '--cfg-path', '/tmp/tmpkob1fzeq']
[2024-03-04T21:47:58.199+0000] {standard_task_runner.py:88} INFO - Job 145: Subtask save_to_csv
[2024-03-04T21:47:58.279+0000] {task_command.py:423} INFO - Running <TaskInstance: scrape_to_csv.save_to_csv scheduled__2023-12-18T00:00:00+00:00 [running]> on host 03972fe0138c
[2024-03-04T21:47:58.405+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='nduti' AIRFLOW_CTX_DAG_ID='scrape_to_csv' AIRFLOW_CTX_TASK_ID='save_to_csv' AIRFLOW_CTX_EXECUTION_DATE='2023-12-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-18T00:00:00+00:00'
[2024-03-04T21:47:58.408+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: save_to_csv() missing 1 required positional argument: 'quotes'
[2024-03-04T21:47:58.421+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=scrape_to_csv, task_id=save_to_csv, execution_date=20231218T000000, start_date=20240304T214758, end_date=20240304T214758
[2024-03-04T21:47:58.441+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 145 for task save_to_csv (save_to_csv() missing 1 required positional argument: 'quotes'; 1735)
[2024-03-04T21:47:58.487+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-04T21:47:58.514+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
