[2024-03-04T21:54:36.909+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrape_and_save_to_csv.save_to_csv scheduled__2023-11-19T00:00:00+00:00 [queued]>
[2024-03-04T21:54:36.936+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrape_and_save_to_csv.save_to_csv scheduled__2023-11-19T00:00:00+00:00 [queued]>
[2024-03-04T21:54:36.938+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-03-04T21:54:36.978+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): save_to_csv> on 2023-11-19 00:00:00+00:00
[2024-03-04T21:54:37.002+0000] {standard_task_runner.py:60} INFO - Started process 2055 to run task
[2024-03-04T21:54:37.010+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'scrape_and_save_to_csv', 'save_to_csv', 'scheduled__2023-11-19T00:00:00+00:00', '--job-id', '225', '--raw', '--subdir', 'DAGS_FOLDER/mydag.py', '--cfg-path', '/tmp/tmpjsi1wako']
[2024-03-04T21:54:37.013+0000] {standard_task_runner.py:88} INFO - Job 225: Subtask save_to_csv
[2024-03-04T21:54:37.160+0000] {task_command.py:423} INFO - Running <TaskInstance: scrape_and_save_to_csv.save_to_csv scheduled__2023-11-19T00:00:00+00:00 [running]> on host 03972fe0138c
[2024-03-04T21:54:37.337+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='nduti' AIRFLOW_CTX_DAG_ID='scrape_and_save_to_csv' AIRFLOW_CTX_TASK_ID='save_to_csv' AIRFLOW_CTX_EXECUTION_DATE='2023-11-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-19T00:00:00+00:00'
[2024-03-04T21:54:37.341+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: save_to_csv() missing 1 required positional argument: 'quotes'
[2024-03-04T21:54:37.355+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=scrape_and_save_to_csv, task_id=save_to_csv, execution_date=20231119T000000, start_date=20240304T215436, end_date=20240304T215437
[2024-03-04T21:54:37.381+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 225 for task save_to_csv (save_to_csv() missing 1 required positional argument: 'quotes'; 2055)
[2024-03-04T21:54:37.426+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-04T21:54:37.467+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
