[2024-03-04T21:54:38.510+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrape_and_save_to_csv.save_to_csv scheduled__2023-11-20T00:00:00+00:00 [queued]>
[2024-03-04T21:54:38.543+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrape_and_save_to_csv.save_to_csv scheduled__2023-11-20T00:00:00+00:00 [queued]>
[2024-03-04T21:54:38.544+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-03-04T21:54:38.954+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): save_to_csv> on 2023-11-20 00:00:00+00:00
[2024-03-04T21:54:38.975+0000] {standard_task_runner.py:60} INFO - Started process 2061 to run task
[2024-03-04T21:54:38.980+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'scrape_and_save_to_csv', 'save_to_csv', 'scheduled__2023-11-20T00:00:00+00:00', '--job-id', '227', '--raw', '--subdir', 'DAGS_FOLDER/mydag.py', '--cfg-path', '/tmp/tmp4l4rr1qe']
[2024-03-04T21:54:38.984+0000] {standard_task_runner.py:88} INFO - Job 227: Subtask save_to_csv
[2024-03-04T21:54:39.105+0000] {task_command.py:423} INFO - Running <TaskInstance: scrape_and_save_to_csv.save_to_csv scheduled__2023-11-20T00:00:00+00:00 [running]> on host 03972fe0138c
[2024-03-04T21:54:39.275+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='nduti' AIRFLOW_CTX_DAG_ID='scrape_and_save_to_csv' AIRFLOW_CTX_TASK_ID='save_to_csv' AIRFLOW_CTX_EXECUTION_DATE='2023-11-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-20T00:00:00+00:00'
[2024-03-04T21:54:39.278+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: save_to_csv() missing 1 required positional argument: 'quotes'
[2024-03-04T21:54:39.294+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=scrape_and_save_to_csv, task_id=save_to_csv, execution_date=20231120T000000, start_date=20240304T215438, end_date=20240304T215439
[2024-03-04T21:54:39.324+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 227 for task save_to_csv (save_to_csv() missing 1 required positional argument: 'quotes'; 2061)
[2024-03-04T21:54:39.368+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-04T21:54:39.403+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
