[2024-03-04T22:35:53.266+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: scrape_n_save_to_csv.scrape_quotes scheduled__2024-02-20T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
