[2024-03-04T21:55:32.499+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrape_and_save_to_csv.save_to_csv manual__2024-03-04T21:54:20.095976+00:00 [queued]>
[2024-03-04T21:55:32.513+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrape_and_save_to_csv.save_to_csv manual__2024-03-04T21:54:20.095976+00:00 [queued]>
[2024-03-04T21:55:32.514+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2024-03-04T21:55:32.534+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): save_to_csv> on 2024-03-04 21:54:20.095976+00:00
[2024-03-04T21:55:32.544+0000] {standard_task_runner.py:60} INFO - Started process 2082 to run task
[2024-03-04T21:55:32.549+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'scrape_and_save_to_csv', 'save_to_csv', 'manual__2024-03-04T21:54:20.095976+00:00', '--job-id', '233', '--raw', '--subdir', 'DAGS_FOLDER/mydag.py', '--cfg-path', '/tmp/tmptz1i9w3d']
[2024-03-04T21:55:32.551+0000] {standard_task_runner.py:88} INFO - Job 233: Subtask save_to_csv
[2024-03-04T21:55:32.616+0000] {task_command.py:423} INFO - Running <TaskInstance: scrape_and_save_to_csv.save_to_csv manual__2024-03-04T21:54:20.095976+00:00 [running]> on host 03972fe0138c
[2024-03-04T21:55:32.714+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='nduti' AIRFLOW_CTX_DAG_ID='scrape_and_save_to_csv' AIRFLOW_CTX_TASK_ID='save_to_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-03-04T21:54:20.095976+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-04T21:54:20.095976+00:00'
[2024-03-04T21:55:32.717+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: save_to_csv() missing 1 required positional argument: 'quotes'
[2024-03-04T21:55:32.728+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=scrape_and_save_to_csv, task_id=save_to_csv, execution_date=20240304T215420, start_date=20240304T215532, end_date=20240304T215532
[2024-03-04T21:55:32.743+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 233 for task save_to_csv (save_to_csv() missing 1 required positional argument: 'quotes'; 2082)
[2024-03-04T21:55:32.760+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-04T21:55:32.783+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
